name: golangci-lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.go"
      - "**/go.mod"
      - .github/workflows/golangci-lint.yaml

jobs:
  golangci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --enable gofmt --disable structcheck
          working-directory: ${{ github.workspace }}/tools/cn-tree-simulator
